<?php declare(strict_types=1);
// [method, path, access, purpose, permission]
// access: public | public+rate-limit | admin-entry (no session; origin-checked) | admin (staff session + permission)
return [
 ['GET','/api/v1/health','public','health'],
 ['GET','/api/v1/readiness','public','readiness'],
 ['GET','/api/v1/content','public','published content'],
 ['GET','/api/v1/navigation','public','navigation'],
 ['GET','/api/v1/products','public','published products'],
 ['GET','/api/v1/services','public','published services'],
 ['GET','/api/v1/careers','public','published careers'],
 ['POST','/api/v1/forms/{form_key}/submit','public+rate-limit','form submission'],
 ['GET','/api/v1/media/{id}/{filename}','public','media library file (images shown, documents downloaded)'],
 ['GET','/api/v1/pages/{page}','public','a page\'s published text (built-in wording fills the rest)'],
 ['POST','/api/v1/analytics/pageview','public','cookieless page view (always 204; bots and Do Not Track ignored)'],
 ['GET','/api/v1/admin/setup','admin-entry','first administrator setup available?'],
 ['POST','/api/v1/admin/setup','admin-entry','create the first administrator (one-time setup code)'],
 ['POST','/api/v1/admin/session','admin-entry','staff sign-in (throttled)'],
 ['GET','/api/v1/admin/session','admin','current staff member',null],
 ['DELETE','/api/v1/admin/session','admin','sign out',null],
 ['POST','/api/v1/admin/session/password','admin','change own password',null],
 ['POST','/api/v1/admin/session/mfa','admin','second sign-in step: authenticator or recovery code (throttled)',null],
 ['POST','/api/v1/admin/password-reset','admin-entry','staff forgot-password: emails a one-time reset link; same answer for any address (throttled, D-016)'],
 ['POST','/api/v1/admin/password-reset/complete','admin-entry','staff forgot-password: sets a new password with the emailed link and signs out everywhere (D-016)'],
 ['GET','/api/v1/admin/account/two-factor','admin','own two-factor status',null],
 ['POST','/api/v1/admin/account/two-factor/setup','admin','start authenticator set-up',null],
 ['POST','/api/v1/admin/account/two-factor/enable','admin','confirm set-up; returns recovery codes once',null],
 ['POST','/api/v1/admin/account/two-factor/recovery-codes','admin','replace recovery codes (needs a current code)',null],
 ['POST','/api/v1/admin/account/two-factor/disable','admin','turn off own two-factor (not for administrators)',null],
 ['GET','/api/v1/admin/enquiries','admin','enquiries inbox','enquiries.read'],
 ['GET','/api/v1/admin/enquiries/{id}','admin','enquiry detail','enquiries.read'],
 ['PATCH','/api/v1/admin/enquiries/{id}','admin','change enquiry status','enquiries.update'],
 ['GET','/api/v1/admin/users','admin','staff accounts','users.manage'],
 ['POST','/api/v1/admin/users','admin','create staff account','users.manage'],
 ['PATCH','/api/v1/admin/users/{id}','admin','update staff account','users.manage'],
 ['POST','/api/v1/admin/users/{id}/two-factor/reset','admin','reset another person\'s two-factor (lost phone)','users.manage'],
 ['GET','/api/v1/admin/audit','admin','audit log','audit.read'],
 ['GET','/api/v1/admin/catalog/{type}','admin','list products or services with draft status','content.edit'],
 ['POST','/api/v1/admin/catalog/{type}','admin','create a hidden product or service','content.edit'],
 ['GET','/api/v1/admin/catalog/{type}/{id}','admin','item with live content, draft and history','content.edit'],
 ['POST','/api/v1/admin/catalog/{type}/{id}/draft','admin','save draft changes','content.edit'],
 ['DELETE','/api/v1/admin/catalog/{type}/{id}/draft','admin','discard the draft','content.edit'],
 ['POST','/api/v1/admin/catalog/{type}/{id}/publish','admin','put the draft live','content.publish'],
 ['POST','/api/v1/admin/catalog/{type}/{id}/visibility','admin','show or hide on the website','content.publish'],
 ['POST','/api/v1/admin/catalog/{type}/{id}/revisions/{revision}/restore','admin','copy an earlier version into the draft','content.edit'],
 ['GET','/api/v1/admin/media','admin','media library with upload limits','content.edit'],
 ['POST','/api/v1/admin/media','admin','upload an image or document (raw body, up to 10 MB)','content.edit'],
 ['PATCH','/api/v1/admin/media/{id}','admin','change an image description or document title','content.edit'],
 ['DELETE','/api/v1/admin/media/{id}','admin','delete a file no item uses','content.publish'],
 ['GET','/api/v1/admin/analytics','admin','visitor analytics for 7, 30 or 90 days','analytics.read'],
 ['GET','/api/v1/admin/pages','admin','editable pages with draft status','content.edit'],
 ['GET','/api/v1/admin/pages/{page}','admin','a page\'s fields, live text, draft and history','content.edit'],
 ['POST','/api/v1/admin/pages/{page}/draft','admin','save page text as a draft','content.edit'],
 ['DELETE','/api/v1/admin/pages/{page}/draft','admin','discard the page draft','content.edit'],
 ['POST','/api/v1/admin/pages/{page}/publish','admin','put the page draft live','content.publish'],
 ['POST','/api/v1/admin/pages/{page}/revisions/{revision}/restore','admin','copy an earlier page version into the draft','content.edit'],
];
