/**
 * Built-in copy of the ten industries (database/018, SRS 4.6), shown when the API
 * cannot be read. Related items are resolved against the built-in products and
 * services in lib/catalog.ts. A unit test keeps this in step with the migration.
 */
export const FALLBACK_INDUSTRIES = [
  {
    slug: "financial-services",
    name: "Financial Services",
    icon: "banknote",
    summary: "Software for payments, financial operations and automation, built with the reliability, traceability and security that money demands.",
    description: "Financial products depend on trust. Every transaction has to be accounted for, every failure recoverable and every change traceable.\n\nWe design and build fintech platforms, payment integrations and back-office automation with those requirements at the core, and we are designing Paxofi Pay on the same principles. Regulated activities stay with licensed partners; our part is the software.",
    points: ["Payment and collection integrations", "Financial operations and reconciliation tools", "Back-office process automation", "Secure APIs for partners and channels"],
    related: ["product:paxofi-pay", "service:api-platform-development", "service:software-web-engineering", "service:cloud-infrastructure-foundations"],
  },
  {
    slug: "education",
    name: "Education",
    icon: "graduation-cap",
    summary: "Learning platforms, student portals and training systems that make teaching, enrolment and administration easier to run.",
    description: "Schools, training providers and universities need systems that students, staff and parents can use without friction, often on a phone and a modest connection.\n\nWe build learning and training platforms, student and parent portals, and the administration tools behind them, designed to be accessible and simple to maintain.",
    points: ["Learning and training platforms", "Student and parent portals", "Enrolment, fees and records management", "Online assessments and certificates"],
    related: ["service:software-web-engineering", "service:product-strategy-prototyping", "service:digital-transformation"],
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    icon: "heart-pulse",
    summary: "Health information systems and appointment platforms designed with privacy, reliability and ease of use in mind.",
    description: "Health providers handle some of the most sensitive information there is, and their staff have little time for systems that get in the way.\n\nWe design health information systems, appointment and scheduling platforms and patient-facing services with privacy and access control from the start, and with workflows shaped around the people who use them.",
    points: ["Appointment and scheduling platforms", "Health information and records systems", "Patient portals and reminders", "Reporting for operations and management"],
    related: ["service:software-web-engineering", "service:api-platform-development", "service:cloud-infrastructure-foundations"],
  },
  {
    slug: "retail-commerce",
    name: "Retail & Commerce",
    icon: "shopping-cart",
    summary: "E-commerce, inventory and customer management systems that help businesses sell online and run their stores efficiently.",
    description: "Selling today means running a shop, a website and several digital channels at once, and keeping stock, orders and customers in step across all of them.\n\nWe build online stores, inventory and order systems and customer relationship tools, and connect them to the payment and delivery services a business already uses.",
    points: ["Online stores and e-commerce", "Inventory and order management", "Customer relationship (CRM) tools", "Payment and delivery integrations"],
    related: ["service:software-web-engineering", "service:digital-marketing-growth", "service:api-platform-development", "product:paxofi-pay"],
  },
  {
    slug: "logistics-transportation",
    name: "Logistics & Transportation",
    icon: "truck",
    summary: "Fleet management and tracking systems that give operators a clear, current view of vehicles, deliveries and drivers.",
    description: "Logistics depends on knowing where things are and what happens next. Paper and spreadsheets stop keeping up once a fleet or delivery network grows.\n\nWe build fleet and delivery management systems, tracking dashboards and customer notifications, and connect them to the devices and services already in use.",
    points: ["Fleet and vehicle management", "Shipment and delivery tracking", "Dispatch and route planning tools", "Customer delivery notifications"],
    related: ["service:software-web-engineering", "service:api-platform-development", "service:cloud-infrastructure-foundations"],
  },
  {
    slug: "government",
    name: "Government",
    icon: "landmark",
    summary: "Digital public services and workflow automation that make it simpler for citizens to get things done and for agencies to deliver.",
    description: "Public services work best when people can complete them online, clearly and securely, and when the processes behind them are automated and auditable.\n\nWe design and build digital service portals, case and workflow systems and records management, treating accessibility, security and audit trails as requirements rather than extras.",
    points: ["Online service and application portals", "Workflow and case management", "Records and document management", "Accessible, auditable systems"],
    related: ["service:digital-transformation", "service:software-web-engineering", "service:cloud-infrastructure-foundations"],
  },
  {
    slug: "agriculture",
    name: "Agriculture",
    icon: "sprout",
    summary: "Agritech platforms and farm management tools that help producers, cooperatives and buyers plan, track and trade.",
    description: "Agriculture runs on timing, weather and markets, and many producers still manage it on paper.\n\nWe build farm management and record-keeping tools, cooperative and out-grower platforms, and marketplaces that connect producers with buyers, designed to work well on a phone in the field.",
    points: ["Farm management and record keeping", "Cooperative and out-grower platforms", "Produce marketplaces and ordering", "Mobile-first tools for the field"],
    related: ["service:product-strategy-prototyping", "service:software-web-engineering", "service:api-platform-development"],
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    icon: "factory",
    summary: "Production and operations management systems that connect planning, the factory floor and reporting.",
    description: "Manufacturers need to know what is being produced, with what, and at what cost. Disconnected spreadsheets make that hard.\n\nWe build production planning, inventory and quality systems and operational dashboards that bring the data together, connected to existing equipment and business software where possible.",
    points: ["Production planning and tracking", "Materials and inventory management", "Quality and maintenance records", "Operational dashboards and reporting"],
    related: ["service:digital-transformation", "service:software-web-engineering", "service:api-platform-development"],
  },
  {
    slug: "non-profit",
    name: "Non-Profit Organisations",
    icon: "hand-heart",
    summary: "Donation platforms and volunteer management systems that help charities and NGOs raise funds and coordinate their people.",
    description: "Non-profit organisations need to reach supporters, account for every donation and coordinate volunteers, usually with small teams and tight budgets.\n\nWe build donation and fundraising platforms, volunteer and programme management tools and clear reporting, kept simple to run and maintain.",
    points: ["Donation and fundraising platforms", "Volunteer management", "Programme and beneficiary records", "Reporting for donors and boards"],
    related: ["service:software-web-engineering", "service:digital-marketing-growth", "product:paxofi-pay"],
  },
  {
    slug: "startups-smes",
    name: "Startups & SMEs",
    icon: "rocket",
    summary: "Digital transformation, software development and business automation for growing companies, from first product to scale.",
    description: "Startups and small businesses need technology that fits their stage: a product that can be tested quickly, systems that save time, and foundations that will not need rebuilding as they grow.\n\nWe help shape and prototype products, build web and mobile applications, automate routine work and set up reliable hosting, and we are building PaxofiCloud to make that infrastructure easier to buy and manage.",
    points: ["Product strategy and prototypes", "Web and mobile applications", "Business process automation", "Hosting, domains and cloud set-up"],
    related: ["service:product-strategy-prototyping", "service:software-web-engineering", "service:digital-transformation", "product:paxoficloud"],
  },
];
